version: "3.8"

services:
  task:
    build:
      context: ..
      dockerfile: task2/docker/Dockerfile
    container_name: task2
    restart: always
    ports:
      - "8100:8100"
    env_file:
      - .env
    depends_on:
      - immudb

  immudb:
    image: codenotary/immudb:latest
    container_name: immudb
    ports:
      - "3322:3322"
    volumes:
      - immudb_data:/var/lib/immudb
    restart: always

volumes:
  immudb_data:
  